# CMake generated Testfile for 
# Source directory: /home/rabuske/NS3/source/ns-3.26/gccxml/GCC_XML/Testing
# Build directory: /home/rabuske/NS3/source/ns-3.26/gccxml-build/GCC_XML/Testing
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(gxConfiguration.cxx "/home/rabuske/NS3/source/ns-3.26/gccxml-build/bin/gccxml" "-I/home/rabuske/NS3/source/ns-3.26/gccxml-build/GCC_XML/GXFront" "-I/home/rabuske/NS3/source/ns-3.26/gccxml-build/GCC_XML" "-I/home/rabuske/NS3/source/ns-3.26/gccxml-build/GCC_XML/GXFront" "-I/home/rabuske/NS3/source/ns-3.26/gccxml/GCC_XML/GXFront" "/home/rabuske/NS3/source/ns-3.26/gccxml/GCC_XML/GXFront/gxConfiguration.cxx" "-fxml=gxConfiguration.cxx.gcc.xml")
add_test(gxConfiguration.h "/home/rabuske/NS3/source/ns-3.26/gccxml-build/bin/gccxml" "-I/home/rabuske/NS3/source/ns-3.26/gccxml-build/GCC_XML/GXFront" "-I/home/rabuske/NS3/source/ns-3.26/gccxml-build/GCC_XML" "-I/home/rabuske/NS3/source/ns-3.26/gccxml-build/GCC_XML/GXFront" "-I/home/rabuske/NS3/source/ns-3.26/gccxml/GCC_XML/GXFront" "/home/rabuske/NS3/source/ns-3.26/gccxml/GCC_XML/GXFront/gxConfiguration.h" "-fxml=gxConfiguration.h.gcc.xml")
add_test(gxDocumentation.cxx "/home/rabuske/NS3/source/ns-3.26/gccxml-build/bin/gccxml" "-I/home/rabuske/NS3/source/ns-3.26/gccxml-build/GCC_XML/GXFront" "-I/home/rabuske/NS3/source/ns-3.26/gccxml-build/GCC_XML" "-I/home/rabuske/NS3/source/ns-3.26/gccxml-build/GCC_XML/GXFront" "-I/home/rabuske/NS3/source/ns-3.26/gccxml/GCC_XML/GXFront" "/home/rabuske/NS3/source/ns-3.26/gccxml/GCC_XML/GXFront/gxDocumentation.cxx" "-fxml=gxDocumentation.cxx.gcc.xml")
add_test(gxDocumentation.h "/home/rabuske/NS3/source/ns-3.26/gccxml-build/bin/gccxml" "-I/home/rabuske/NS3/source/ns-3.26/gccxml-build/GCC_XML/GXFront" "-I/home/rabuske/NS3/source/ns-3.26/gccxml-build/GCC_XML" "-I/home/rabuske/NS3/source/ns-3.26/gccxml-build/GCC_XML/GXFront" "-I/home/rabuske/NS3/source/ns-3.26/gccxml/GCC_XML/GXFront" "/home/rabuske/NS3/source/ns-3.26/gccxml/GCC_XML/GXFront/gxDocumentation.h" "-fxml=gxDocumentation.h.gcc.xml")
add_test(gxFlagsParser.cxx "/home/rabuske/NS3/source/ns-3.26/gccxml-build/bin/gccxml" "-I/home/rabuske/NS3/source/ns-3.26/gccxml-build/GCC_XML/GXFront" "-I/home/rabuske/NS3/source/ns-3.26/gccxml-build/GCC_XML" "-I/home/rabuske/NS3/source/ns-3.26/gccxml-build/GCC_XML/GXFront" "-I/home/rabuske/NS3/source/ns-3.26/gccxml/GCC_XML/GXFront" "/home/rabuske/NS3/source/ns-3.26/gccxml/GCC_XML/GXFront/gxFlagsParser.cxx" "-fxml=gxFlagsParser.cxx.gcc.xml")
add_test(gxFlagsParser.h "/home/rabuske/NS3/source/ns-3.26/gccxml-build/bin/gccxml" "-I/home/rabuske/NS3/source/ns-3.26/gccxml-build/GCC_XML/GXFront" "-I/home/rabuske/NS3/source/ns-3.26/gccxml-build/GCC_XML" "-I/home/rabuske/NS3/source/ns-3.26/gccxml-build/GCC_XML/GXFront" "-I/home/rabuske/NS3/source/ns-3.26/gccxml/GCC_XML/GXFront" "/home/rabuske/NS3/source/ns-3.26/gccxml/GCC_XML/GXFront/gxFlagsParser.h" "-fxml=gxFlagsParser.h.gcc.xml")
add_test(gxFront.cxx "/home/rabuske/NS3/source/ns-3.26/gccxml-build/bin/gccxml" "-I/home/rabuske/NS3/source/ns-3.26/gccxml-build/GCC_XML/GXFront" "-I/home/rabuske/NS3/source/ns-3.26/gccxml-build/GCC_XML" "-I/home/rabuske/NS3/source/ns-3.26/gccxml-build/GCC_XML/GXFront" "-I/home/rabuske/NS3/source/ns-3.26/gccxml/GCC_XML/GXFront" "/home/rabuske/NS3/source/ns-3.26/gccxml/GCC_XML/GXFront/gxFront.cxx" "-fxml=gxFront.cxx.gcc.xml")
add_test(gxSystemTools.cxx "/home/rabuske/NS3/source/ns-3.26/gccxml-build/bin/gccxml" "-I/home/rabuske/NS3/source/ns-3.26/gccxml-build/GCC_XML/GXFront" "-I/home/rabuske/NS3/source/ns-3.26/gccxml-build/GCC_XML" "-I/home/rabuske/NS3/source/ns-3.26/gccxml-build/GCC_XML/GXFront" "-I/home/rabuske/NS3/source/ns-3.26/gccxml/GCC_XML/GXFront" "/home/rabuske/NS3/source/ns-3.26/gccxml/GCC_XML/GXFront/gxSystemTools.cxx" "-fxml=gxSystemTools.cxx.gcc.xml")
add_test(gxSystemTools.h "/home/rabuske/NS3/source/ns-3.26/gccxml-build/bin/gccxml" "-I/home/rabuske/NS3/source/ns-3.26/gccxml-build/GCC_XML/GXFront" "-I/home/rabuske/NS3/source/ns-3.26/gccxml-build/GCC_XML" "-I/home/rabuske/NS3/source/ns-3.26/gccxml-build/GCC_XML/GXFront" "-I/home/rabuske/NS3/source/ns-3.26/gccxml/GCC_XML/GXFront" "/home/rabuske/NS3/source/ns-3.26/gccxml/GCC_XML/GXFront/gxSystemTools.h" "-fxml=gxSystemTools.h.gcc.xml")
add_test(TestFullPathInclude.cxx "/home/rabuske/NS3/source/ns-3.26/gccxml-build/bin/gccxml" "-I/home/rabuske/NS3/source/ns-3.26/gccxml-build/GCC_XML/GXFront" "-I/home/rabuske/NS3/source/ns-3.26/gccxml-build/GCC_XML" "-I/home/rabuske/NS3/source/ns-3.26/gccxml-build/GCC_XML/GXFront" "-I/home/rabuske/NS3/source/ns-3.26/gccxml/GCC_XML/GXFront" "/home/rabuske/NS3/source/ns-3.26/gccxml-build/GCC_XML/Testing/TestFullPathInclude.cxx" "-fxml=TestFullPathInclude.cxx.gcc.xml")
add_test(TestUsualInclude.cxx "/home/rabuske/NS3/source/ns-3.26/gccxml-build/bin/gccxml" "-I/home/rabuske/NS3/source/ns-3.26/gccxml-build/GCC_XML/GXFront" "-I/home/rabuske/NS3/source/ns-3.26/gccxml-build/GCC_XML" "-I/home/rabuske/NS3/source/ns-3.26/gccxml-build/GCC_XML/GXFront" "-I/home/rabuske/NS3/source/ns-3.26/gccxml/GCC_XML/GXFront" "/home/rabuske/NS3/source/ns-3.26/gccxml/GCC_XML/Testing/TestUsualInclude.cxx" "-fxml=TestUsualInclude.cxx.gcc.xml")
